# set PUB_HOSTED_URL=https://pub.flutter-io.cn
# set FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn

name: hanabi_download_manager_x
description: A EASY AND BEAUTIFUL DOWNLOAD MANAGER
publish_to: 'none'
version: 1.5.0+20260924

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  crypto: ^3.0.7
  cryptography: ^2.7.0
  intl: ^0.20.2
  uuid: ^4.5.3
  path: ^1.8.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  material_symbols_icons: ^4.2719.1
  fluent_ui: ^4.13.0
  window_manager: ^0.5.1
  tray_manager: ^0.5.2
  file_selector: ^1.0.3
  url_launcher: ^6.3.0
  package_info_plus: ^10.1.0
  win32: ^6.3.0
  ffi: ^2.1.0
  screen_retriever: ^0.2.0
  google_fonts: ^8.1.0
  fl_chart: ^1.2.0
  scroll_animator: ^0.3.0
  rhttp: 0.18.0
  flutter_markdown_plus: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  flutter_rust_bridge: 2.12.0
  matcher: 0.12.20
  meta: 1.18.3
  test_api: 0.7.12
  vector_math: 2.4.0
  path_provider_android: 2.2.23

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/logo/logo.svg
    - assets/logo/logo.png
    - assets/logo/logo.ico
    - assets/logo/color_logo/
    - assets/flags/
    - assets/font/FluentSystemIcons-Regular.json
  
  fonts:
    - family: FluentSystemIcons
      fonts:
        - asset: assets/font/FluentSystemIcons-Regular.ttf
